### ISSUE TITLE
Special characters not properly encoded in VIAF search

### ISSUE THREAD

**Issue by timathom** [UMiamiLibraries/RAMP#100]
The initial VIAF search doesn't seem to be properly encoding names with special characters.

For example, a RAMP search for "Arredondo Gutiérrez, Alberto" returns "No results found!" 

However, a VIAF search for http://viaf.org/viaf/search?query=local.names+all+%22Arredondo%20Guti%C3%A9rrez,%20Alberto%22&sortKeys=holdingscount&recordSchema=BriefVIAF shows that there is a result in VIAF.

If you look at the query that's actually being sent to VIAF by RAMP, this is how it's being encoded:

`Arredondo+Guti%C3%83%C2%83%C3%82%C2%A9rrez%2C+Alberto`

A search for http://viaf.org/viaf/search?query=local.names+all+"Arredondo+Guti%C3%83%C2%83%C3%82%C2%A9rrez%2C+Alberto"&sortKeys=holdingscount&recordSchema=BriefVIAF does not return any results.

**Comment by little9** [comment]
It looks to me like there are a lot of unnecessary functions for encoding and decoding strings being used all over the place. I've simplified them and gotten the searches working correctly. I'll go back and remove them later.
