### ISSUE TITLE
cpfRelationType attribute bug

### ISSUE THREAD

**Issue by timathom** [UMiamiLibraries/RAMP#103]
If a user tries to add a CPF relation element but does not choose a relation type, no default value is added for the `cpfRelationType` attribute. This causes a validation error in the XML view.

The default value for this attribute should be `associative` and the default value for the `xlink:type` attribute should be `simple`.

**Comment by agdarby** [comment]
Hey Tim, just to make sure:  are these issues (this plus the other 3) testing vs. the development branch?

**Comment by timathom** [comment]
Yes, tested using the latest Docker image (https://hub.docker.com/r/umiamilibraries/ramp/).

**Comment by little9** [comment]
This causes issue #107
