### ISSUE TITLE
Must load EAC first when choosing VIAF for Yolanda Arenas

### ISSUE THREAD

**Issue by mlemusrojas** [UMiamiLibraries/RAMP#105]
When clicking on VIAF after selecting the file, a message saying "Must load EAC first!" comes up
![yolanda arenas](https://cloud.githubusercontent.com/assets/15731780/16178262/12f6ac98-3611-11e6-89fc-4811e0334edc.png)

**Comment by little9** [comment]
I'll check the XML for that record, maybe it is invalid or not well-formed in a unique way.

**Comment by little9** [comment]
I think this must have just been a random mishap because when I load the VIAF step for this record it works for me.
