### ISSUE TITLE
WorldCat Step 1 (instructional text duplicated)

### ISSUE THREAD

**Issue by mlemusrojas** [UMiamiLibraries/RAMP#106]
![rosa abella_instructional text duplicated](https://cloud.githubusercontent.com/assets/15731780/16178280/8f1d5254-3611-11e6-9379-7f7395fe4f8c.png)

**Comment by little9** [comment]
I'll look into this and see if it's caused by a template calling this twice or something with that specific record.

**Comment by little9** [comment]
I can't duplicate this issue on my install. It looks like this for me:

![screen shot 2016-06-20 at 3 08 28 pm](https://cloud.githubusercontent.com/assets/4324761/16206957/d66cb07c-36f8-11e6-84ef-c1621af16d06.png)
