### ISSUE TITLE
VIAF step 1 skipped

### ISSUE THREAD

**Issue by mlemusrojas** [UMiamiLibraries/RAMP#108]
![viaf step 1 skipped](https://cloud.githubusercontent.com/assets/15731780/16178329/c985d9c4-3612-11e6-925f-6dc6e0b66593.png)

**Comment by timathom** [comment]
Duplicate of issues #100 and #101. There are two problems:

* Names with special characters are not properly encoded, which causes the search to return no results.
* When there actually are no results for a search, the user should be notified.
