### ISSUE TITLE
JSON.parse error on Wiki step

### ISSUE THREAD

**Issue by timathom** [UMiamiLibraries/RAMP#115]
Our old friend Arredondo is still causing trouble. The attached file (saved as .txt) makes it through the first two steps, but then gets stuck on a parsing error at the Wiki step. Nothing seems odd about this record at first glance. I've tested a few others that worked fine. 

Oops, I just tried another one that throws the same error (also attached).

<img width="1280" alt="screenshot 2016-06-21 17 15 57" src="https://cloud.githubusercontent.com/assets/5334524/16246775/b2aa6ca6-37d4-11e6-931c-a9d5de1f88df.png">

[arredondo_alberto_papers.txt](https://github.com/UMiamiLibraries/RAMP/files/326622/arredondo_alberto_papers.txt)
[baquero_gastn_papers.txt](https://github.com/UMiamiLibraries/RAMP/files/326641/baquero_gastn_papers.txt)

**Comment by little9** [comment]
ᚢᛏᚠ᛫ᛇᚷᚺᛏ᛫ᛈᚱᛟᛒᛚᛖᛗ
ᚹᛁᛚᛚ᛫ᛖᛜᚲᛟᛞᛖ᛫ᛚᚨᛏᛖᚱ

**Comment by timathom** [comment]
Uh-oh. Maybe I should just close this issue and go whistling on my way. . . .

**Comment by little9** [comment]
Haha! I think it's caused by the special characters in the names. Should be a quick fix.
