### ISSUE TITLE
JSON parse error in Wikipedia (step 1)_Alberto Arredondo

### ISSUE THREAD

**Issue by mlemusrojas** [UMiamiLibraries/RAMP#118]

**Comment by little9** [comment]
I just fixed this. It will be a while before it's pushed to the Docker image. 

You can use it at:
https://tools.wmflabs.org/ramp/index.php

**Comment by timathom** [comment]
Cool! But are there database issues going on with the demo site? 

When I try to select a record, I get the "Must load EAC first error.

When I click "All Items," I get a PHP error: 

`Fatal error: Call to a member function bind_param() on a non-object in /data/project/ramp/public_html/lib/RAMP/Ingest/IngestStatus.php on line 32`
