### ISSUE TITLE
Demo site issues

### ISSUE THREAD

**Issue by timathom** [UMiamiLibraries/RAMP#119]
On https://tools.wmflabs.org/ramp/index.php, when I try to select a record, I get the `Must load EAC first` error when selecting WorldCat or VIAF steps.

When I click "All Items," I get a PHP error:

`Fatal error: Call to a member function bind_param() on a non-object in /data/project/ramp/public_html/lib/RAMP/Ingest/IngestStatus.php on line 32`

**Comment by little9** [comment]
Should be ok now

**Comment by timathom** [comment]
Nice!!!
