### ISSUE TITLE
User is stuck after Cancel Button 

### ISSUE THREAD

**Issue by pvillanueva01** [UMiamiLibraries/RAMP#51]
takes you to prev state but "Process Icons" remain disabled so user cannot go anywhere

![screen shot 2016-02-22 at 12 28 29 pm](https://cloud.githubusercontent.com/assets/8170097/13226543/d69dd31a-d95f-11e5-96c1-d05eace8c6ef.png)

**Comment by cgb37** [comment]
Fixed #51 - user is redirected to save xml screen and wiki button is activated
