### ISSUE TITLE
WorldCat Step 2 needs a "Skip" button

### ISSUE THREAD

**Issue by pvillanueva01** [UMiamiLibraries/RAMP#52]
Step 2 is not required to continue to XML screen

**Comment by cgb37** [comment]
Fixed #52 - Added skip button to step two of world cat ingest and shows user ace editor with save buttons

**Comment by pvillanueva01** [comment]
When skipping step 2 and then saving the XML file, VIAF is not available. This does not happen if a selection is made on step 2 :-(

![screen shot 2016-02-22 at 2 50 20 pm](https://cloud.githubusercontent.com/assets/8170097/13230558/d2b94612-d973-11e5-9a29-995dd15964e2.png)

**Comment by little9** [comment]
There is a skip button for WorldCat on step two and the related issue that @pvillanueva01 mentioned doesn't happen anymore.
